import {QueryClient,QueryClientProvider} from '@tanstack/react-query';import {render,screen,fireEvent,waitFor} from '@testing-library/react';import {beforeEach,expect,it,vi} from 'vitest';import {TokenDetailView} from './token-detail-view';
const {detail,listings,ownership,trade,request,add}=vi.hoisted(()=>({detail:vi.fn(),listings:vi.fn(),ownership:vi.fn(),trade:vi.fn(),request:vi.fn(),add:vi.fn()}));
vi.mock('@/lib/marketplace/hooks',()=>({useTokenDetailQuery:detail,useCollectionListingsQuery:listings}));vi.mock('./use-token-ownership',()=>({useTokenOwnership:ownership}));vi.mock('@/lib/marketplace/use-trade',()=>({useTrade:trade}));vi.mock('@/lib/marketplace/api-client',()=>({marketplaceRequest:request}));vi.mock('@/features/cart/hooks/use-add-to-cart-feedback',()=>({useAddToCartFeedback:()=>({addListingToCart:add})}));
vi.mock('@/features/trading/best-bid',()=>({BestBid:()=>null}));
vi.mock('@/features/trading/order-composer',()=>({OrderComposer:({kind}:{kind:string})=><div>{kind} composer</div>}));vi.mock('@/features/trading/accept-offer',()=>({AcceptOffer:()=> <button>Review offer</button>}));vi.mock('@/features/trading/report-token',()=>({ReportToken:()=> <button>Report token</button>}));
function show(){return render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><TokenDetailView address="0xa" tokenId="1"/></QueryClientProvider>);}
beforeEach(()=>{detail.mockReturnValue({data:{token:{contract_address:'0xa',token_id:'1',metadata:{name:'Realm One',description:'A realm',attributes:[{trait_type:'Power',value:42}]}}},refetch:vi.fn()});listings.mockReturnValue({data:[]});ownership.mockReturnValue({effectiveIsOwner:false,holderAddress:'0x2'});trade.mockReturnValue({address:'0x3',config:{chain:'LOCAL',demo:false},busy:false,state:{stage:'idle',message:''},execute:vi.fn()});request.mockResolvedValue({items:[],nextCursor:null});add.mockReset();});
it('retains token identity, traits, ownership and reporting',async()=>{show();expect(screen.getByText('Realm One')).toBeInTheDocument();expect(screen.getByText('Power')).toBeInTheDocument();expect(screen.getByText('42')).toBeInTheDocument();expect(screen.getByText('Owner: 0x2')).toBeInTheDocument();await waitFor(()=>expect(screen.getByText('Report token')).toBeInTheDocument());});
it('offers a listing composer only to the owner',()=>{ownership.mockReturnValue({effectiveIsOwner:true,holderAddress:'0x3'});show();expect(screen.getByText('listing composer')).toBeInTheDocument();expect(screen.queryByText('token_offer composer')).toBeNull();});
it('offers token bids to nonowners',()=>{show();expect(screen.getByText('token_offer composer')).toBeInTheDocument();});
it('renders loading before offering trades',()=>{detail.mockReturnValue({isLoading:true});show();expect(screen.getByText('Loading token…')).toBeInTheDocument();expect(screen.queryByText('token_offer composer')).toBeNull();});
it('offers retry without fake token content on failure',()=>{const refetch=vi.fn();detail.mockReturnValue({isError:true,refetch});show();expect(screen.getByRole('alert')).toHaveTextContent('Unable to load this token');fireEvent.click(screen.getByText('Retry'));expect(refetch).toHaveBeenCalled();});
it('requires a proceeds review for matching collection and token offers',async()=>{ownership.mockReturnValue({effectiveIsOwner:true});request.mockImplementation((path:string)=>Promise.resolve({items:path.endsWith('/offers')?[{id:'a',kind:'collection_offer',tokenId:null,buyerDebit:'100',currency:'0x1'},{id:'b',kind:'token_offer',tokenId:'1',buyerDebit:'200',currency:'0x1'},{id:'c',kind:'token_offer',tokenId:'2',buyerDebit:'300',currency:'0x1'}]:[]}));show();await waitFor(()=>expect(screen.getAllByText('Review offer')).toHaveLength(2));});
