import {OperatorPanel} from "./operator-panel";
import {render,screen,fireEvent,waitFor} from '@testing-library/react';import {beforeEach,expect,it,vi} from 'vitest';import {OpsStatusPanel} from './ops-status-panel';
const {config,refresh}=vi.hoisted(()=>({config:vi.fn(),refresh:vi.fn()}));
vi.mock('@/lib/marketplace/react',()=>({useMarketConfig:config}));
vi.mock('@/lib/marketplace/config',()=>({getMarketplaceRuntimeConfig:()=>({chainLabel:'LOCAL'})}));
beforeEach(()=>{config.mockReturnValue({data:{chain:'LOCAL',demo:false,status:{safeForCheckout:false,indexedBlock:10,chainHead:15,lagBlocks:5,reasons:['INDEX_STALE']}},refetch:refresh});vi.unstubAllGlobals();});
it('shows actual progress and disables readiness when indexing is stale',()=>{render(<OpsStatusPanel/>);expect(screen.getByText('Trading temporarily unavailable')).toBeInTheDocument();expect(screen.getByText('Marketplace data is being updated. Please check again shortly.')).toBeInTheDocument();expect(screen.getByText('5')).toBeInTheDocument();fireEvent.click(screen.getByText('Refresh status'));expect(refresh).toHaveBeenCalled();});
it('does not expose operator queries without explicit credentials',()=>{render(<OpsStatusPanel/>);expect(screen.queryByText('Load reports')).not.toBeInTheDocument();expect(screen.queryByLabelText('Operator access token')).not.toBeInTheDocument();});
it('sends credentials only on an explicit operator request and renders errors',async()=>{const fetch=vi.fn().mockResolvedValue({ok:false,json:async()=>({error:{message:'Invalid operator credential'}})});vi.stubGlobal('fetch',fetch);render(<OperatorPanel/>);fireEvent.change(screen.getByLabelText('Operator access token'),{target:{value:'test-secret'}});fireEvent.click(screen.getByText('Load reports'));await waitFor(()=>expect(screen.getByText('Invalid operator credential')).toBeInTheDocument());expect(fetch).toHaveBeenCalledWith('/api/marketplace/v1/chains/LOCAL/operator/reports',expect.objectContaining({headers:{authorization:'Bearer test-secret'}}));});
